### ISSUE TITLE
possible error

### ISSUE THREAD

**Issue by GitM10** [machine1337/pdfcrack#9]
I've got this error:

Traceback (most recent call last):
  File "/home/kali/pdfcrack/pdfcrack.py", line 87, in <module>
    crack()
  File "/home/kali/pdfcrack/pdfcrack.py", line 60, in crack
    header()
  File "/home/kali/pdfcrack/pdfcrack.py", line 6, in header
    ascii_banner = pyfiglet.figleet_format("{PDF CRACKER}").upper()
                   ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pyfiglet' has no attribute 'figleet_format'. Did you mean: 'figlet_format'?

i fix this by replacing 'figleet_format' with 'figlet_format'

**Comment by jowagner** [comment]
Fixed with commit 3e47e90a79b54d78f5ccc2af76ba145a7d8ae142.
